# Based off https://github.com/MinecraftForge/SharedActions/blob/main/.github/workflows/gradle.yml
name: Gradle publishing CI

on:
  workflow_call:
    inputs:
      java:
        description: "The version of Java to use to run Gradle" # Note: Gradle's Java toolchains feature is used for compiling, which is separate from this
        required: false
        type: string
        default: "17"
      version_task:
        description: "The Gradle task that outputs the version"
        required: false
        type: string
        default: ""
      pre_gradle_tasks:
        description: "The Gradle task(s) to run pre-publication"
        required: false
        type: string
        default: ""
      gradle_tasks:
        description: "The Gradle task(s) to run at publication"
        required: false
        type: string
        default: "publish"
      version_labels:
        description: "Optional configuration for version labels"
        required: false
        type: "string"
        default: ""
    secrets:
      DISCORD_WEBHOOK:
        required: true
      
      MAVEN_USER:
        required: false
      MAVEN_PASSWORD:
        required: false
      MAVEN_URL_RELEASE:
        required: false
      
      SONATYPE_USER:
        required: false
      SONATYPE_PASSWORD:
        required: false
        
      GPG_PRIVATE_KEY:
        required: false
      GPG_KEY_PASSWORD:
        required: false

      GPG_SUBKEY:
        required: false
      GPG_SUBKEY_ID:
        required: false
      GPG_SUBKEY_PASSWORD:
        required: false

      GPP_KEY:
        required: false
      GPP_SECRET:
        required: false

permissions:
  contents: read
  statuses: write

jobs:
  compute-version:
    name: Compute version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ inputs.version_task && steps.gradle.outputs.version || steps.version.outputs.version }}
    steps:
      - uses: neoforged/action-tag-versioning@v1
        name: Calculate version
        id: version
        if: ${{ !inputs.version_task }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: ${{ inputs.version_labels }}
      - uses: actions/checkout@v4
        if: inputs.version_task
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Make Gradle executable
        # language=bash
        run: chmod +x ./gradlew # Thanks Windows
        if: inputs.version_task

      - name: Setup Java ${{ inputs.java }}
        if: inputs.version_task
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
        # language=bash
        run: |
          echo "JAVA_HOME=$(echo $JAVA_HOME_${{ inputs.java }}_X64)" >> "$GITHUB_ENV"

      - name: Validate wrapper
        if: inputs.version_task
        uses: gradle/actions/wrapper-validation@v3

      - name: Gradle version task
        uses: gradle/gradle-build-action@v2
        if: inputs.version_task
        id: gradle
        with:
          arguments: ${{ inputs.version_task }}

  notify-build-start:
    needs: ["compute-version"]
    name: Build notifications (start)
    runs-on: ubuntu-latest
    steps:
      - uses: neoforged/action-webhooks@v1
        name: Send Discord start notification
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          status: 'started'
          version: ${{ needs.compute-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: neoforged/action-github-status@v1
        name: Set pending status
        with:
           authToken: ${{secrets.GITHUB_TOKEN}}
           context: 'Publishing'
           state: 'pending'
           description: "Version: ${{ needs.compute-version.outputs.version }}"
           target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  gradle:
    needs: ["compute-version"] # Make sure we now the version before starting to build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Make Gradle executable
        # language=bash
        run: chmod +x ./gradlew # Thanks Windows

      - name: Setup Java ${{ inputs.java }}
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
        # language=bash
        run: |
          echo "JAVA_HOME=$(echo $JAVA_HOME_${{ inputs.java }}_X64)" >> "$GITHUB_ENV"

      - name: Validate wrapper
        uses: gradle/actions/wrapper-validation@v3
        
      - name: Gradle pre-publication tasks
        uses: gradle/gradle-build-action@v2
        if: inputs.pre_gradle_tasks
        with:
          arguments: ${{ inputs.pre_gradle_tasks }}

      - name: Gradle ${{ inputs.gradle_tasks }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ inputs.gradle_tasks }}
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
          GPG_SUBKEY: ${{ secrets.GPG_SUBKEY }}
          GPG_SUBKEY_ID: ${{ secrets.GPG_SUBKEY_ID }}
          GPG_SUBKEY_PASSWORD: ${{ secrets.GPG_SUBKEY_PASSWORD }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPP_KEY: ${{ secrets.GPP_KEY }}
          GPP_SECRET: ${{ secrets.GPP_SECRET }}
          MAVEN_URL_RELEASE: ${{ secrets.MAVEN_URL_RELEASE }}

  notify-build-end:
    name: Build notifications (end)
    needs: [ "compute-version", "notify-build-start", "gradle" ]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: neoforged/action-webhooks@v1
        name: Send Discord end notification
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ needs.gradle.result }}
          version: ${{ needs.compute-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: neoforged/action-github-status@v1
        name: Set build status
        with:
           authToken: ${{ secrets.GITHUB_TOKEN }}
           context: 'Publishing'
           state: ${{ needs.gradle.result }}
           description: "Version: ${{ needs.compute-version.outputs.version }}"
           target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
